version: 2.1

orbs:
  maven: circleci/maven@0.0.12

workflows:
  maven_test:
    jobs:
      - maven/test # checkout, build, test, and upload test results
      - image: circleci/mysql:8.0.4
        auth:
          username: monty
          password: some_pass
